\pset format csv
\echo validate_acres
\o cuws.sql.validate_acres.csv
\i cuws.sql.validate_acres.sql
\echo validate_bogs_mowed
\o cuws.sql.validate_bogs_mowed.csv
\i cuws.sql.validate_bogs_mowed.sql
\echo validate_bogs_renovated
\o cuws.sql.validate_bogs_renovated.csv
\i cuws.sql.validate_bogs_renovated.sql
\echo validate_contract_number
\o cuws.sql.validate_contract_number.csv
\i cuws.sql.validate_contract_number.sql
\echo validate_field_bog_name
\o cuws.sql.validate_field_bog_name.csv
\i cuws.sql.validate_field_bog_name.sql
\echo cuws.sql.validate_field_location
\o cuws.sql.validate_field_location.csv
\i cuws.sql.validate_field_location.sql
\echo validate_field_name_and_location
\o cuws.sql.validate_field_name_and_location.csv
\i cuws.sql.validate_field_name_and_location.sql
\echo validate_location_and_contract
\o cuws.sql.validate_location_and_contract.csv
\i cuws.sql.validate_location_and_contract.sql
\echo validate_location_and_pid
\o cuws.sql.validate_location_and_pid.csv
\i cuws.sql.validate_location_and_pid.sql
\echo validate_pid_and_contract
\o cuws.sql.validate_pid_and_contract.csv
\i cuws.sql.validate_pid_and_contract.sql
\echo validate_pid_and_location
\o cuws.sql.validate_pid_and_location.csv
\i cuws.sql.validate_pid_and_location.sql
\echo validate_pid_empty
\o cuws.sql.validate_pid_empty.csv
\i cuws.sql.validate_pid_empty.sql
\echo validate_pid_malformed
\o cuws.sql.validate_pid_malformed.csv
\i cuws.sql.validate_pid_malformed.sql
\echo validate_spacing
\o cuws.sql.validate_spacing.csv
\i cuws.sql.validate_spacing.sql
\echo validate_variety_name
\o cuws.sql.validate_variety_name.csv
\i cuws.sql.validate_variety_name.sql
\echo validate_year_planted
\o cuws.sql.validate_year_planted.csv
\i cuws.sql.validate_year_planted.sql
\o
\pset format aligned
