export const SCOPE_APPLICATION_PREFIX = "CIRRAS_UNDERWRITING.";

export const SCOPES_UI = {
    GET_TOP_LEVEL: `${SCOPE_APPLICATION_PREFIX}GET_TOP_LEVEL`,
    GET_CODE_TABLES: `${SCOPE_APPLICATION_PREFIX}GET_CODE_TABLES`,
    SEARCH_UWCONTRACTS: `${SCOPE_APPLICATION_PREFIX}SEARCH_UWCONTRACTS`,

    GET_UWCONTRACT: `${SCOPE_APPLICATION_PREFIX}GET_UWCONTRACT`,
    CREATE_INVENTORY_CONTRACT: `${SCOPE_APPLICATION_PREFIX}CREATE_INVENTORY_CONTRACT`,
    GET_INVENTORY_CONTRACT: `${SCOPE_APPLICATION_PREFIX}GET_INVENTORY_CONTRACT`,
    SEARCH_ANNUAL_FIELDS: `${SCOPE_APPLICATION_PREFIX}SEARCH_ANNUAL_FIELDS`,
    UPDATE_INVENTORY_CONTRACT: `${SCOPE_APPLICATION_PREFIX}UPDATE_INVENTORY_CONTRACT`,
    DELETE_INVENTORY_CONTRACT: `${SCOPE_APPLICATION_PREFIX}DELETE_INVENTORY_CONTRACT`,
    GET_LEGAL_LAND: `${SCOPE_APPLICATION_PREFIX}GET_LEGAL_LAND`,
    CREATE_LEGAL_LAND: `${SCOPE_APPLICATION_PREFIX}CREATE_LEGAL_LAND`,
    UPDATE_LEGAL_LAND: `${SCOPE_APPLICATION_PREFIX}UPDATE_LEGAL_LAND`,
    DELETE_LEGAL_LAND: `${SCOPE_APPLICATION_PREFIX}DELETE_LEGAL_LAND`,

    CREATE_DOP_YIELD_CONTRACT: `${SCOPE_APPLICATION_PREFIX}CREATE_DOP_YIELD_CONTRACT`,
    GET_YIELD_MEAS_UNIT_TYPE_CODES: `${SCOPE_APPLICATION_PREFIX}GET_YIELD_MEAS_UNIT_TYPE_CODES`,
    GET_DOP_YIELD_CONTRACT: `${SCOPE_APPLICATION_PREFIX}GET_DOP_YIELD_CONTRACT`,
    GET_GRADE_MODIFIERS: `${SCOPE_APPLICATION_PREFIX}GET_GRADE_MODIFIERS`,
    SAVE_GRADE_MODIFIERS: `${SCOPE_APPLICATION_PREFIX}SAVE_GRADE_MODIFIERS`,
    UPDATE_DOP_YIELD_CONTRACT: `${SCOPE_APPLICATION_PREFIX}UPDATE_DOP_YIELD_CONTRACT`,
    DELETE_DOP_YIELD_CONTRACT: `${SCOPE_APPLICATION_PREFIX}DELETE_DOP_YIELD_CONTRACT`,
    PRINT_DOP_YIELD_CONTRACT: `${SCOPE_APPLICATION_PREFIX}PRINT_DOP_YIELD_CONTRACT`,

    CREATE_VERIFIED_YIELD_CONTRACT : `${SCOPE_APPLICATION_PREFIX}CREATE_VERIFIED_YIELD_CONTRACT`,
    GET_VERIFIED_YIELD_CONTRACT : `${SCOPE_APPLICATION_PREFIX}GET_VERIFIED_YIELD_CONTRACT`,
    UPDATE_VERIFIED_YIELD_CONTRACT : `${SCOPE_APPLICATION_PREFIX}UPDATE_VERIFIED_YIELD_CONTRACT`,
    DELETE_VERIFIED_YIELD_CONTRACT : `${SCOPE_APPLICATION_PREFIX}DELETE_VERIFIED_YIELD_CONTRACT`,

    DELETE_COMMENTS: `${SCOPE_APPLICATION_PREFIX}DELETE_COMMENTS`,

    GET_UNDERWRITING_YEAR: `${SCOPE_APPLICATION_PREFIX}GET_UNDERWRITING_YEAR`,
    CREATE_UNDERWRITING_YEAR: `${SCOPE_APPLICATION_PREFIX}CREATE_UNDERWRITING_YEAR`,
    DELETE_UNDERWRITING_YEAR: `${SCOPE_APPLICATION_PREFIX}DELETE_UNDERWRITING_YEAR`,

    GET_SEEDING_DEADLINES: `${SCOPE_APPLICATION_PREFIX}GET_SEEDING_DEADLINES`,
    SAVE_SEEDING_DEADLINES: `${SCOPE_APPLICATION_PREFIX}SAVE_SEEDING_DEADLINES`,

    GET_CROP_VARIETY_INSURABILITIES: `${SCOPE_APPLICATION_PREFIX}GET_CROP_VARIETY_INSURABILITIES`,
    SAVE_CROP_VARIETY_INSURABILITIES: `${SCOPE_APPLICATION_PREFIX}SAVE_CROP_VARIETY_INSURABILITIES`,

    GET_YIELD_MEAS_UNIT_CONVERSIONS: `${SCOPE_APPLICATION_PREFIX}GET_YIELD_MEAS_UNIT_CONVERSIONS`,
    SAVE_YIELD_MEAS_UNIT_CONVERSIONS: `${SCOPE_APPLICATION_PREFIX}SAVE_YIELD_MEAS_UNIT_CONVERSIONS`,

    SEARCH_USER_SETTING: `${SCOPE_APPLICATION_PREFIX}SEARCH_USER_SETTING`,
    GET_USER_SETTING: `${SCOPE_APPLICATION_PREFIX}GET_USER_SETTING`,
    CREATE_USER_SETTING: `${SCOPE_APPLICATION_PREFIX}CREATE_USER_SETTING`,
    UPDATE_USER_SETTING: `${SCOPE_APPLICATION_PREFIX}UPDATE_USER_SETTING`,

};

export const ROLES_UI = {
  UNDERWRITING_SUPER_ADMIN: `${SCOPE_APPLICATION_PREFIX}UNDERWRITING_SUPER_ADMIN`,
  UNDERWRITING_WRITE: `${SCOPE_APPLICATION_PREFIX}UNDERWRITING_WRITE`,
  UNDERWRITING_READ: `${SCOPE_APPLICATION_PREFIX}UNDERWRITING_READ`,
};

export const ROUTE_SCOPES = {
  LANDING                               : [SCOPES_UI.GET_TOP_LEVEL, SCOPES_UI.GET_CODE_TABLES, SCOPES_UI.SEARCH_UWCONTRACTS, SCOPES_UI.SEARCH_USER_SETTING],
  INVENTORY                             : [SCOPES_UI.GET_INVENTORY_CONTRACT],
  DOP                                   : [SCOPES_UI.GET_DOP_YIELD_CONTRACT, SCOPES_UI.GET_YIELD_MEAS_UNIT_TYPE_CODES, SCOPES_UI.GET_GRADE_MODIFIERS],
  VERIFIED_YEILD                        : [SCOPES_UI.GET_VERIFIED_YIELD_CONTRACT],
  LEGAL_LAND                            : [SCOPES_UI.GET_LEGAL_LAND],
  MAINTAIN                              : [SCOPES_UI.GET_UNDERWRITING_YEAR],
  MAINTAIN_SEEDING_DEADLINES            : [SCOPES_UI.GET_SEEDING_DEADLINES, SCOPES_UI.GET_UNDERWRITING_YEAR],
  MAINTAIN_GRADE_MODIFIERS              : [SCOPES_UI.GET_UNDERWRITING_YEAR, SCOPES_UI.GET_GRADE_MODIFIERS],
  MAINTAIN_FORAGE_VARIETY_INSURABILITY  : [SCOPES_UI.GET_CROP_VARIETY_INSURABILITIES],
  MAINTAIN_YIELD_CONVERSION             : [SCOPES_UI.GET_YIELD_MEAS_UNIT_CONVERSIONS , SCOPES_UI.SAVE_YIELD_MEAS_UNIT_CONVERSIONS ],
  USER_SETTINGS                         : [SCOPES_UI.GET_TOP_LEVEL, SCOPES_UI.SEARCH_USER_SETTING, SCOPES_UI.GET_USER_SETTING]
}