#Docker Compose for local-only build

services:
  client:
    build: cirras-underwriting-war
    ports:
      - "8085:8080"
    environment:
      - CIRRAS_UNDERWRITING_REST_URI=http://vivid-w133.vividsolutions.com:8086/cirras-underwriting-api/v1
      - WEBADE_OAUTH2_AUTHORIZE_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/oauth/authorize
      - WEBADE_OAUTH2_ENABLE_CHECKTOKEN=true
      - LOCAL_CHECKTOKEN_ENDPOINT=checkToken.jsp
      - WEBADE_CHECK_TOKEN_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/check_token?disableDeveloperFilter=true
      - WEBADE_OAUTH2_SITEMINDER_URL=https://logontest.gov.bc.ca/clp-cgi/logoff.cgi?returl\=
      - WEBADE_CIRRAS_UNDERWRITING_UI_SECRET=password
      - WEBADE_GET_TOKEN_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/oauth/token
      - WEBADE_OAUTH2_SCOPES=CIRRAS_UNDERWRITING.*
      - WEBADE_OAUTH2_SITEMINDER_URL=https://logontest.gov.bc.ca/clp-cgi/logoff.cgi?returl=
      - ACTIVE_PORT=8085
      - WEB_PATH=/pub/cirras_underwriting

  api:
    build: cirras-underwriting-api
    ports: 
      - "8086:8080"
    environment:
      - WEBADE_GET_TOKEN_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/oauth/token
      - WEBADE_CHECK_TOKEN_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/check_token?disableDeveloperFilter=true
      - WEBADE_USERNAME=PROXY_WEBADE_BOOTSTRAP
      - WEBADE_PASSWORD=password
      - WEBADE_MAXACTIVE=10
      - POSTGRES_RESOURCE_NAME=cirras_underwriting_rest
      - POSTGRES_URL=jdbc:postgresql://pgsql01.vividsolutions.com:5432/cirras_dev
      - POSTGRES_USERNAME=proxy_cuws_rest
      - POSTGRES_PASSWORD=password
      - POSTGRES_MAXACTIVE=10
      - CIRRAS_UNDERWRITING_REST_CLIENT_ID=CIRRAS_UNDERWRITING_REST
      - CIRRAS_UNDERWRITING_REST_SECRET=password
      - CIRRAS_POLICIES_API_URL=
      - JASPER_URL=
      - JASPER_USERNAME=
      - JASPER_PASSWORD=

  listener-api:
    build: cirras-underwriting-listener-api
    ports: 
      - "8087:8080"
    environment:
      - WEBADE_GET_TOKEN_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/oauth/token
      - WEBADE_CHECK_TOKEN_URL=https://d1auth.vividsolutions.com/pub/webade-oauth2/check_token?disableDeveloperFilter=true
      - WEBADE_USERNAME=PROXY_WEBADE_BOOTSTRAP
      - WEBADE_PASSWORD=password
      - WEBADE_MAXACTIVE=10
      - POSTGRES_RESOURCE_NAME=failover
      - POSTGRES_URL=jdbc:postgresql://pgsql01.vividsolutions.com:5432/cirras_dev
      - POSTGRES_USERNAME=proxy_cuws_rest
      - POSTGRES_PASSWORD=password
      - POSTGRES_MAXACTIVE=10
      - CIRRAS_UNDERWRITING_REST_URI=http://vivid-w133.vividsolutions.com:8086/cirras-underwriting-api/v1
      - CIRRAS_UNDERWRITING_SYNC_USER=CIRRAS_UNDERWRITING_SYNC_REST
      - CIRRAS_UNDERWRITING_SYNC_SECRET=password
      - ACTIVEMQ_URL=
      - ACTIVEMQ_EMAIL_ERROR_FREQ=
      - DEFAULT_APPLICATION_ENV=
      - ACTIVEMQ_EMAIL_ERROR_SUBJECT=
      - ACTIVEMQ_ADMIN_EMAILS=
      - ACTIVEMQ_EMAIL_HOSTNAME=
      - ACTIVEMQ_EMAIL_PORT=
      - ACTIVEMQ_EMAIL_FROM_ADDRESS=
  
  # postgresql:
  #   image: postgres:15.6
  #   ports: 
  #     - "8432:5432"