--Insert Blueberry
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 0, 0, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 0 AND scale = 0 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 1, 0.05, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 1 AND scale = 0.05 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 2, 0.11, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 2 AND scale = 0.11 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 3, 0.23, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 3 AND scale = 0.23 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 4, 0.32, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 4 AND scale = 0.32 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 5, 0.52, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 5 AND scale = 0.52 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 6, 0.64, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 6 AND scale = 0.64 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY'), 7, 0.79, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 7 AND scale = 0.79 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'BLUEBERRY') );

--Insert Raspberry
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'RASPBERRY'), 0, 0.5, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 0 AND scale = 0.5 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'RASPBERRY') );

--Insert Cranberry
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY'), 0, 0, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 0 AND scale = 0 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY'), 1, 0.04, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 1 AND scale = 0.04 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY'), 2, 0.33, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 2 AND scale = 0.33 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY') );
INSERT INTO cuws.commodity_maturity_scale(commodity_maturity_scale_guid, crop_commodity_id, plant_age, scale, version_number, effective_crop_year, expiry_crop_year, create_user, create_date, update_user, update_date) SELECT replace(cast(gen_random_uuid() as text), '-', ''), (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY'), 3, 0.59, 1, 2026, 9999, 'CUWS_04_01_00', now(),  'CUWS_04_01_00', now()WHERE NOT EXISTS (SELECT NULL FROM commodity_maturity_scale WHERE plant_age = 3 AND scale = 0.59 and crop_commodity_id = (select crop_commodity_id from crop_commodity where commodity_name = 'CRANBERRY') );
