INSERT INTO cuws.berries_2026_staging(
        input_line_number,
        contract_number,
        crop_year,
        grower_contract_year_id,
        contract_id,
        property_identifier,
        primary_property_identifier,
        primary_land_identifier_type_code,
        secondary_property_identifiers,
        legal_land_id,
        bog_id,
        field_bog_name,
        field_id,
        crop_name,
        crop_commodity_id,
        field_location,
        field_order,
        planting_number,
        year_planted,
        acres,
        ownership,
        variety_name,
        crop_variety_id,
        row_spacing,
        plant_spacing,
        bogs_mowed,
        bogs_renovated,
        harvested_ind,
        is_quantity_insurable_ind,
        is_plant_insurable_ind,
        plant_insurability_type_code,
        do_insert_legal_land_ind
) VALUES 
-- Add data here
;
