-- Role: "PROXY_DAP_PIUW_DEV"
-- DROP ROLE "PROXY_DAP_PIUW_DEV";

CREATE ROLE "PROXY_DAP_PIUW_DEV" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD '${POSTGRES_PROXY_DAP_PASSWORD}';
  
ALTER ROLE "PROXY_DAP_PIUW_DEV" SET search_path TO cuws;

COMMENT ON ROLE "PROXY_DAP_PIUW_DEV" IS 'Proxy account for DAP read only access to Cirras Underwriting System in DVLR';

--GRANT "app_cuws_readonly" TO "PROXY_DAP_PIUW_DEV";