kind: ConfigMap
apiVersion: v1
metadata:
  name: cirras-underwriting-liquibase-config-#{ENV}#
  namespace: '#{NAMESPACE}#'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-04-15T22:11:17Z'
      fieldsType: FieldsV1
  labels:
    app: cirras-underwriting-api-#{ENV}#
    project: brmb-pim-#{ENV}#
immutable: false
data:
  LIQUIBASE_COMMAND_USERNAME: '#{POSTGRES_ADMIN_USERNAME}#'
  LIQUIBASE_COMMAND_PASSWORD: '#{POSTGRES_ADMIN_PASSWORD}#'
  LIQUIBASE_COMMAND_URL: jdbc:postgresql://crunchy-postgres-#{ENV}#-pgbouncer.#{NAMESPACE}#.svc.cluster.local/pituw#{ENV}#
  POSTGRES_PROXY_USER_PASSWORD: '#{POSTGRES_PROXY_USER_PASSWORD}#'
  POSTGRES_READ_ONLY_PASSWORD: '#{POSTGRES_READ_ONLY_PASSWORD}#'
