apiVersion: v1
kind: ConfigMap
metadata:
  name: 'cirras-underwriting-jasper-config-#{ENV}#'
  namespace: '#{NAMESPACE}#'
data:
  ALLOW_EMPTY_PASSWORD: '#{ALLOW_EMPTY_PASSWORD}#'
  JASPERREPORTS_DATABASE_NAME: '#{JASPERREPORTS_DATABASE_NAME}#'
  JASPERREPORTS_UI_USER: '#{JASPERREPORTS_UI_USER}#'
binaryData: {}
immutable: false
