apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasper-#{ENV}#
  namespace: '#{NAMESPACE}#'
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Mi