apiVersion: v1
kind: Service
metadata:
  name: cirras-underwriting-api-service-#{ENV}#
  namespace: '#{NAMESPACE}#'
spec:
  selector:
    app: cirras-underwriting-api-#{ENV}#
  ports:
    - protocol: TCP
      port: #{TOMCAT_PORT}#
      targetPort: #{TOMCAT_PORT}#
