name: build and deploy reports

on: 
  workflow_dispatch:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: choice
        options:
          - dev
          - qa
          - int
          - dlvr
          - test
          - prod
      NAMESPACE:
        required: true
        type: choice
        options: 
          - a12541-dev
          - a12541-test
          - a12541-prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fill xml files
        uses: cschleiden/replace-tokens@v1.2
        with: 
          files: cirras-underwriting-reports-jrs/**/*.xml
        env:
          CUWS_ds_0_url: "jdbc:postgresql://crunchy-postgres-pgbouncer.${{vars.LICENSE_PLATE}}-${{ inputs.ENVIRONMENT_NAME }}.svc.cluster.local/cirras${{inputs.ENVIRONMENT_NAME}}"
          CUWS_ds_0_user: "${{ secrets.POSTGRES_READONLY_USERNAME }}"
          CUWS_ds_0_password: "${{ secrets.POSTGRES_READONLY_PASSWORD }}"

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Make report zipfile
        run: |
          cd cirras-underwriting-reports-jrs/src/main
          zip export.zip ./*
          export AUTHORIZATION="Basic $(echo ${{vars.JASPER_USER}}:${{vars.JASPER_PASSWORD}} | base64)"
          export JASPER_URL="https://cirras-underwriting-jasper-route-${{ inputs.ENVIRONMENT_NAME}}-${{ inputs.NAMESPACE}}.apps.silver.devops.gov.bc.ca/jasperserver/rest_v2/import?keyAlias=deprecatedImportExportEncSecret&update=true"
          curl -X POST $JASPER_URL -H "Content-Type: application/zip" -H "Authorization: $AUTHORIZATION" -T export.zip

      - uses: actions/upload-artifact@v4
        with:
          name: export.zip
          path: cirras-underwriting-reports-jrs/src/main/export.zip
