name: Build .war and npm files

on:
  workflow_dispatch:
    inputs:
      TAG:
          required: true
          type: string
          description: Additional tag to apply to images being built
          default: latest

jobs:
  

  build-underwriting-api:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      TAG: ${{ inputs.tag }}
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: cirras-underwriting-api
      EXPORT_FILE: CIRRAS_UNDERWRITING_API_swagger.json
      EXPORT_PATH: cirras-underwriting-api/cirras-underwriting-api-rest-endpoints/target/swagger.json
      JAVA_VERSION: 17
      TAG: ${{ inputs.TAG }}

  build-and-upload-npm-modules:
    uses: ./.github/workflows/build-npm.yml
    secrets: inherit
    needs: build-underwriting-api
    with:
      TAG: ${{ inputs.tag }}
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: cirras-underwriting-ngclient-lib
      DOWNLOAD_FILE: CIRRAS_UNDERWRITING_API_swagger.json
      DOWNLOAD_PATH: cirras-underwriting-ngclient-lib/cirras-underwriting-ngclient-lib/src/main/angular/src/swagger/
      EXPORT_MODULE: cirras-underwriting-api
      NPM_ARTIFACT_PATH: \@cirras/cirras-underwriting-api/-/@cirras

  build-underwriting-war:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    needs: build-and-upload-npm-modules
    with:
      TAG: ${{ inputs.tag }}
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: cirras-underwriting-war
