name: build npm-lib

env:
  NPMRC: ${{ secrets.NPMRC }}
  REPO_PREFIX: na12-pim-libs
  ARTIFACTORY_PATH: ca/bc/gov/mal/cirras/underwriting

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
          required: true
          type: string
      MICROSERVICE_NAME:
          required: true
          type: string
      API_TARGET:
          required: false
          type: string
      SWAGGER_TARGET_PATH:
          required: false
          type: string
      NPM_ARTIFACT_PATH:
          required: true
          type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    name: Build and upload NPM
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Extract version number
        id: getVersion
        run: |
          export VERSION_NUMBER=$(grep -Po -m 1 '(?<=<version>)[0-9\.]+(-SNAPSHOT)?'  ${{ inputs.MICROSERVICE_NAME }}/pom.xml )
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_OUTPUT

      #NOTE: necessary to build client-war 
      - name: Add .npmrc file
        run: echo -e $NPMRC > ~/.npmrc

      - name: Setup artifactory
        uses: jfrog/setup-jfrog-cli@v4

      - name: download swagger file
        run: |
          [[ $(echo "${{ steps.getVersion.outputs.VERSION_NUMBER }}" | grep -o SNAPSHOT ) = SNAPSHOT ]] && REPO_SUFFIX="SNAPSHOT" || REPO_SUFFIX="RELEASE"
          [[ $(echo "${{ steps.getVersion.outputs.VERSION_NUMBER }}" | grep -o SNAPSHOT ) = SNAPSHOT ]] && URL="${{ vars.SNAPSHOT_URL }}" || URL=${{ vars.RELEASE_URL }}
          jfrog rt dl \
          --flat --limit=1 --sort-by=created \
          --sort-order=desc \
          --url=$URL \
          --user=${{ secrets.OPENSHIFT_ACCOUNT }} \
          --password=${{ secrets.OPENSHIFT_PASSWORD }} \
          "$REPO_PREFIX-$REPO_SUFFIX/${{ env.ARTIFACTORY_PATH }}/${{inputs.API_TARGET}}-rest-endpoints/${{ steps.getVersion.outputs.VERSION_NUMBER }}/${{inputs.API_TARGET}}-rest-endpoints-${{ steps.getVersion.outputs.VERSION_NUMBER }}-swagger.json" \
          ${{inputs.SWAGGER_TARGET_PATH}}
      
      - name: npm install
        run: |
          cd ${{ inputs.MICROSERVICE_NAME }}/${{ inputs.MICROSERVICE_NAME }}/src/main/angular 
          npm install
          npm run generate
          npm run build
          cd dist/${{ inputs.API_TARGET }}
          npm pack

      - name: Push Build to Artifactory
        run: |
          export VERSION_NUMBER=${{ steps.getVersion.outputs.VERSION_NUMBER }}
          mv ${{ inputs.MICROSERVICE_NAME }}/${{ inputs.MICROSERVICE_NAME }}/src/main/angular/dist/${{ inputs.API_TARGET }}/cirras-${{ inputs.API_TARGET}}-$VERSION_NUMBER.tgz  cirras-${{ inputs.API_TARGET}}-$VERSION_NUMBER.tgz
          export BUILD_NAME="cirras-${{ inputs.API_TARGET}}-$VERSION_NUMBER"
          export BUILD_MODULE="${{ inputs.API_TARGET}}"
          
          jf rt upload  --url ${{ vars.ARTIFACTORY_URL }} --user ${{ secrets.OPENSHIFT_ACCOUNT }} --password ${{ secrets.OPENSHIFT_PASSWORD }} --build-name $BUILD_NAME --module $BUILD_MODULE --target-props npm.version=$VERSION_NUMBER "cirras-${{ inputs.API_TARGET}}-$VERSION_NUMBER.tgz" ${{ vars.NPM_REPO }}/${{ inputs.NPM_ARTIFACT_PATH}}/${{inputs.API_TARGET}}-$VERSION_NUMBER.${{ github.run_number }}.tgz
          
