name: cirras-underwriting-listener-api CI build

on:
  pull_request_target:
    branches:
      - main
    paths:
      - cirras-underwriting-listener-api/**

jobs:
  build-underwriting-listener-api:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: cirras-underwriting-listener-api
