name: cirras-underwriting-war CI build

on:
  pull_request_target:
    branches:
      - main
    paths:
      - cirras-underwriting-war/**

jobs:
  build-underwriting-war:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: cirras-underwriting-war
  
  openshift-deploy:
    uses: ./.github/workflows/openshift-deploy.yml
    secrets: inherit
    with:
      MICROSERVICE_NAME: cirras-underwriting-war
      NAMESPACE: ${{ vars.NAMESPACE }}
      ENVIRONMENT_NAME: dev
