name: cirras-underwriting-api CI build

on:
  pull_request_target:
    branches:
      - main
      - release/*
    paths:
      - cirras-underwriting-api/**

jobs:
  build-underwriting-api:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      ENVIRONMENT: DEV
      MICROSERVICE_NAME: cirras-underwriting-api

  openshift-deploy:
    uses: ./.github/workflows/openshift-deploy.yml
    secrets: inherit
    with:
      MICROSERVICE_NAME: cirras-underwriting-api
      NAMESPACE: ${{ vars.NAMESPACE }}
      ENVIRONMENT_NAME: dev

      
